trigger:
- master
- intel

jobs:
- job: Build
  timeoutInMinutes: 0

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  # Remove the ubuntu-toolchain-r/test PPA, which is added by default. Some
  # packages were removed, and this is causing the g++multilib install to fail.
  # Similar issue: https://github.com/scikit-learn/scikit-learn/issues/13928
    - bash: |
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat
        rm -rf build
        source oe-init-build-env
        bitbake intel-platforms
      displayName: 'Build'
      timeoutInMinutes: 0
      env: { DEBIAN_FRONTEND: noninteractive}
